export const homeStories = [
  {
    image: 'mountains.jpg',
    title: 'The Mountains in September',
    author: 'Davis Moda',
  },
  {
    image: 'cityscapes.jpg',
    title: 'Sunset Cityscapes',
    author: 'Benjamin Cruz',
  },
  {
    image: '18-days-voyage.jpg',
    title: '18 Days Voyage',
    author: 'Alexei Borodin',
  },
  {
    image: 'architecturals.jpg',
    title: 'Architecturals',
    author: 'Samantha Bordin',
  },
  { image: 'world-tour.jpg' },
  { image: 'somwarpet.jpg' },
  { image: 'behind-the-waves.jpg' },
  { image: 'trip-to-nowhere.jpg' },
  { image: 'king-on-africa.jpg' },
  { image: 'running-free.jpg' },
  { image: 'rage-of-the-sea.jpg' },
  { image: 'moon-of-appalacia.jpg' },
  { image: 'dark-forest.jpg' },
  { image: 'milky-way.jpg' },
  { image: 'calm-waters.jpg' },
  { image: 'unforeseen-corners.jpg' },
  { image: 'land-of-dreams.jpg' },
]
